server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://xqbcyjpnvuyymv:fd4a95d5b74b9256112ee8748fe3621ae56cdb10b9f8051ca2f436098eee1c89@ec2-34-232-191-133.compute-1.amazonaws.com:5432/ddk6f69c3eh1nv
    username: xqbcyjpnvuyymv
    password: fd4a95d5b74b9256112ee8748fe3621ae56cdb10b9f8051ca2f436098eee1c89
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para o bootcamp DIO - Santander
  version: 1.0

